These commits update the v8  add ClusterClient support.
elliotchance/redismock pull request #41
Opened 2022-04-07 14:16 UTC by vvlgo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/redismock/41)

2022-04-08 12:11 UTC, elliotchance requested changes

2022-04-08 12:11 UTC, elliotchance commented on v8/client.go
> +	if !m.hasStub("Watch") {
"Process"

2022-04-08 12:11 UTC, elliotchance commented on v8/client.go
> +	ctx    context.Context
How does this get set if the test intends to mock `Context()`? Perhaps call it `Ctx`?

2022-04-08 12:11 UTC, elliotchance commented on v8/client.go
> +	if !m.hasStub("Watch") {
"Do"

2022-04-08 12:11 UTC, elliotchance commented on v8/client.go
> +	if !m.hasStub("Watch") {
"Close"

2022-04-14 03:11 UTC, vvlgo commented
Yes, you are right. I corrected it. Please review this

2022-04-15 17:43 UTC, elliotchance approved these changes

2022-04-15 17:44 UTC, merged